import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
 return (
  <div className={styles.container}>
   <Head>
    <title>we2-chat App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   <main className={styles.main}>
    <h1 className={styles.title}>
     Welcome to <a href="">we2 Chat!</a>
    </h1>

    <p className={styles.description}>
     to learn more visit{" "}
     <a href="https://chat.openai.com/" target="_blank">
      <code className={styles.code}>https://chat.openai.com</code>
     </a>
    </p>

    <div className={styles.grid}>
     <Link href="./chat" className={styles.card}>
      <h2>Chat &rarr;</h2>
      <p>Find in-depth information about Next.js features and API.</p>
     </Link>

     <Link href="https://nextjs.org/learn" className={styles.card}>
      <h2>Bhagvat Gita &rarr;</h2>
      <p>Learn about Next.js in an interactive course with quizzes!</p>
     </Link>

     <Link
      href="https://github.com/vercel/next.js/tree/canary/examples"
      className={styles.card}
     >
      <h2>Examples &rarr;</h2>
      <p>Discover and deploy boilerplate example Next.js projects.</p>
     </Link>

     <Link
      href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
      className={styles.card}
     >
      <h2>About Us &rarr;</h2>
      <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
     </Link>
    </div>
   </main>

   <footer className={styles.footer}>
    <a
     href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
     target="_blank"
     rel="noopener noreferrer"
    >
     Powered by{" "}
     <span className={styles.logo}>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
     </span>
    </a>
   </footer>
  </div>
 );
}
